WebApplication1/Models/Prod/Prod.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Common;

namespace WebApplication1.Models.Prod
{
        public class Method
        {
            public string 從販售項目選出私廚風格(int fCID)
            {
                string sSQL = $"SELECT DISTINCT s.f風格 [風格] " +
                    $"FROM [t販售項目] p " +
                    $"JOIN [t風格] s ON p.fSID = s.fSID " +
                    $"WHERE p.fCID = @fCID ";
                   
                var value = new List<SqlParameter>()
                {
                    new SqlParameter("@fCID",fCID)
                };

                var res = new List<string>();

                DBClass.SQLReader(sSQL, value.ToArray(), (reader) =>
                {
                    while (reader.Read())
                    {
                        res.Add(
                            (string)reader["風格"]
                            );
                    }
                });

                return String.Join(",", res);
            }

            public string 從販售項目選出私廚服務種類(int fCID)
            {
                string sSQL = $"SELECT DISTINCT k.f服務種類 [服務種類] " +
                    $"FROM [t販售項目] p  " +
                    $"JOIN [t服務種類] k ON p.fKID = k.fKID " +
                    $"WHERE p.fCID = @fCID ";

                var value = new List<SqlParameter>()
                {
                    new SqlParameter("@fCID",fCID)
                };

                var res = new List<string>();

                DBClass.SQLReader(sSQL, value.ToArray(), (reader) =>
                {
                    while (reader.Read())
                    {
                        res.Add(
                            (string)reader["服務種類"]
                            );
                    }
                });

                return string.Join(",", res);
            }

    }
}

WebApplication1/ViewModels/Prod/v可預訂時間VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Prod
{
    public class v可預訂時間VM
    {
        public int fCID { get; set; }
        public List<string> ArrEnable { get; set; }
        public List<string> ArrUnable { get; set; }
        public string ArrGetNewTime { get; set; }
        public string ArrGetDeletedTime { get; set; }
    }
}

WebApplication1/ViewModels/Prod/v私廚販售項目清單VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Prod
{

    public class 項目
    {
        public t販售項目 product { get; set; }
        public List<t菜品> dish { get; set; }
    }

    public class v私廚販售項目清單VM
    {
        public t私廚 chef { get; set; }
        public List<項目> prods { get; set; }
    }
}

WebApplication1/ViewModels/Prod/v菜品VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.ViewModels.Prod
{
    public class v菜品VM
    {
        public v菜品VM()
        {
            this.f菜品照片 = WebApplication1.Models.Common.CDictionary.預設NOIMAGE;
        }

        [Key]
        public int fVID { get; set; }

        public string 項目名稱 { get; set; }

        [Display(Name = "產品編號")]
        public int fPID { get; set; }

        [Display(Name = "菜品簡介")]
        [Required(ErrorMessage = "您必須輸入菜品簡介！")]
        public string f菜品簡介 { get; set; }

        [Display(Name = "菜品照片")]
        public string f菜品照片 { get; set; }

        [Display(Name = "菜品名稱")]
        [Required(ErrorMessage = "您必須輸入菜品名稱！")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "請輸入1~20個字")]
        public string f菜品名稱 { get; set; }

        public HttpPostedFileBase image { get; set; }

    }
}

WebApplication1/ViewModels/Prod/v販售項目VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.ViewModels.Prod

{
    public class v販售項目VM
    {
        public v販售項目VM()
        {
            this.f項目照片 = WebApplication1.Models.Common.CDictionary.預設NOIMAGE;
        }

        public int fPID { get; set; }

        public int fCID { get; set; }

        [Display(Name = "風格")]
        public int fSID { get; set; }

        public List<SelectListItem> style { get; set; }

        [Display(Name = "服務種類")]
        public int fKID { get; set; }

        public List<SelectListItem> kind { get; set; }

        [Required(ErrorMessage = "您必須輸入項目名稱")]
        [Display(Name = "項目名稱")]
        public string f項目名稱 { get; set; }

        [Required(ErrorMessage = "您必須輸入項目內容！")]
        [Display(Name = "項目內容")]
        public string f項目內容 { get; set; }

        [Required(ErrorMessage = "您必須輸入價格")]
        [Display(Name = "價格(NT$)")]
        [DataType(DataType.Currency)]
        [Range(100, 10000, ErrorMessage = "價格介於 100 ~ 10000")]
        public int f價格 { get; set; }

        [Display(Name = "上架")]
        [Required]
        public bool f上架 { get; set; }

        public string f項目照片 { get; set; }

        public HttpPostedFileBase image { get; set; }
    }
}

WebApplication1/Controllers/ProdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Common;
using WebApplication1.ViewModels.Prod;
using WebApplication1.Models.SearchResult;

namespace WebApplication1.Controllers
{

    [MyAuthorize(權限 = e會員_權限.私廚)] // 登入驗證 私廚
    public class ProdController : Controller
    {
        // GET: Prod

        private Database1Entities db = new Database1Entities();

        #region 私廚{ [私廚販售項目清單] [新增販售項目] [新增菜色] [設定可預訂時間] }
        //==================================================================================
        // 私廚{ [私廚販售項目清單] [(新增)(編輯)販售項目] [(新增)(編輯)菜色] [設定可預訂時間] }
        //          
        //==================================================================================

        // === [設定可預訂時間] === 
        public ActionResult calendar()
        {
            // 取得此私廚
            var chefId = (int)Session[CDictionary.SK_LOGINED_CHEF_ID];
            // 取得此私廚可預訂時間
            var table = (from t in (new Database1Entities()).t私廚可預訂時間
                         where t.fCID == chefId
                         select t).ToList();

            // 被預訂_不可修改
            var listUnable = new List<string>();
            // 可預定
            var listEnable = new List<string>();

            listUnable.AddRange(
                table
                .Where(t => t.f狀態 == e私廚可預訂_時段_狀態.被預訂_不可修改.GetHashCode())
                .Select(x => x.f日期.ToString("d") + "-" + x.f時段.ToString()).ToList()
                );

            listEnable.AddRange(
                table
                .Where(t => t.f狀態 == e私廚可預訂_時段_狀態.可預定.GetHashCode())
                .Select(x => x.f日期.ToString("d") + "-" + x.f時段.ToString()).ToList()
                );

            var vm = new v可預訂時間VM
            {
                fCID = chefId,
                ArrEnable = listEnable,
                ArrUnable = listUnable
            };

            return View(vm);

        }

        [HttpPost] // 限定 POST
        [ValidateAntiForgeryToken] // 防止 CSRF 跨域偽造請求, 只有從頁面來的才能通過
        public ActionResult calendar(v可預訂時間VM vm)
        {
            // 新增 可預訂時間
            string sCreate = vm.ArrGetNewTime;
            if (!string.IsNullOrEmpty(sCreate))
            {
                // 拆解字串
                string[] ArrSplit = sCreate.Split(',');
                foreach (string s1 in ArrSplit)
                {
                    if (!string.IsNullOrEmpty(s1))
                    {
                        string[] Arr = s1.Split('-');
                        t私廚可預訂時間 t = new t私廚可預訂時間();
                        t.fCID = vm.fCID;
                        t.f日期 = Convert.ToDateTime(Arr[0]);
                        t.f時段 = Convert.ToInt32(Arr[1]);
                        t.f狀態 = e私廚可預訂_時段_狀態.可預定.GetHashCode();
                        db.t私廚可預訂時間.Add(t);
                    }
                }
                // 儲存DB
                db.SaveChanges();
            }

            // 刪除 可預定時間
            string sDelete = vm.ArrGetDeletedTime;

            if (!string.IsNullOrEmpty(sDelete))
            {
                // 拆解字串
                string[] ArrSplitDelete = sDelete.Split(',');
                foreach (string s in ArrSplitDelete)
                {
                    if (!string.IsNullOrEmpty(s))
                    {
                        string[] Arr = s.Split('-');
                        DateTime time = Convert.ToDateTime(Arr[0]);
                        int status = Convert.ToInt32(Arr[1]);
                        var deleteTime = db.t私廚可預訂時間
                            .FirstOrDefault(t => t.f日期 == time && t.f時段 == status && t.fCID == vm.fCID);
                        if (deleteTime != null)
                        {
                            db.t私廚可預訂時間.Remove(deleteTime);
                        }
                    }
                }
                db.SaveChanges();
            }

            TempData[CDictionary.TK_Msg_SaveCalendar] = "儲存成功";

            return RedirectToAction("calendar");
        }

        // === [販售清單列表] ===
        public ActionResult salesItemList(int? fPID)
        {
            var chefId = (int)Session[CDictionary.SK_LOGINED_CHEF_ID];

            var chef = db.t私廚.FirstOrDefault(c => c.fCID == chefId);

            var prods = db.t販售項目.Where(p => p.fCID == chefId).OrderByDescending(p=>p.fPID);

            var 項目清單 = new List<項目>();

            foreach (var item in prods)
            {
                項目清單.Add(new 項目 {
                    product = item,
                    dish = item.t菜品.ToList()
                });
            }

            var vm = new v私廚販售項目清單VM
            {
                chef = chef,
                prods = 項目清單
            };

            ViewBag.that = fPID;

            return View(vm);
        }


        // === 項目創建 === 
        public ActionResult productCreate()
        {
            // 取得 chef
            var chefId = (int)Session[CDictionary.SK_LOGINED_CHEF_ID];

            // 下拉式 //設定風格 SelectListItem
            var selectListStyle = (new CSearchResultFactory()).Add風格SelectListItem();

            // 下拉式 t服務種類
            var selectListKind = (new CSearchResultFactory()).Add服務種類SelectListItem();

            var vm = new v販售項目VM
            {
                fCID = chefId,
                style = selectListStyle,
                kind = selectListKind
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult productCreate(v販售項目VM vm)
        {
            /*  1.建立項目 2.變更私廚風格 3.變更私廚服務種類 */

            // 模型驗證
            if (ModelState.IsValid)
            {

                if (vm.image != null)
                {
                    // 新項目照片地址
                    vm.f項目照片 = (new 共用方法()).照片更新(vm.image, Server.MapPath("~/"), CDictionary.照片存檔位置_項目, "");
                }
                
                // 1.建立項目
                db.t販售項目.Add(new t販售項目
                {
                    fCID = vm.fCID,
                    fSID = vm.fSID,
                    fKID = vm.fKID,
                    f項目名稱 = vm.f項目名稱,
                    f項目內容 = vm.f項目內容,
                    f項目照片 = vm.f項目照片,
                    f價格 = vm.f價格,
                    f上架 = vm.f上架
                });
                // 儲存DB
                db.SaveChanges();

                // 從販售項目選出私廚風格
                var 私廚風格 = (new Models.Prod.Method()).從販售項目選出私廚風格(vm.fCID);
                // 從販售項目選出私廚服務種類
                var 私廚服務種類 = (new Models.Prod.Method()).從販售項目選出私廚服務種類(vm.fCID);

                // 2.變更私廚風格
                // 3.變更私廚服務種類 // 其他方法: 拆解字串 NOT IN 則加入 >> 刪除處理?
                // 找到此私廚
                var chef = db.t私廚.FirstOrDefault(c => c.fCID == vm.fCID);
                chef.f風格 = 私廚風格;
                chef.f服務種類 = 私廚服務種類;
                // 儲存DB
                db.SaveChanges();
                // 回私廚所有項目 // 至新增-販售項目-菜品 無法取得 fPID
                return RedirectToAction("salesItemList");
            }
            // 後端模型驗證失敗 Form物件回傳
            // 下拉式 //設定風格 SelectListItem
            var selectListStyle = (new CSearchResultFactory()).Add風格SelectListItem();
            // 下拉式 t服務種類
            var selectListKind = (new CSearchResultFactory()).Add服務種類SelectListItem();
            // 上一次所選的值
            selectListStyle.First(s => s.Value == vm.fSID.ToString()).Selected = true;
            selectListKind.First(k => k.Value == vm.fKID.ToString()).Selected = true;
            vm.style = selectListStyle;
            vm.kind = selectListKind;

            return View(vm);
        }

        // === 項目編輯 ===
        public ActionResult productEdit(int fPID)
        {
            // 取得此販售項目
            var prod = db.t販售項目.FirstOrDefault(p => p.fPID == fPID);

            // 下拉式 //設定風格 SelectListItem
            var selectListStyle = (new CSearchResultFactory()).Add風格SelectListItem();
            // 下拉式 t服務種類
            var selectListKind = (new CSearchResultFactory()).Add服務種類SelectListItem();
            // 預設值
            selectListStyle.First(x => x.Value == prod.fSID.ToString()).Selected = true;
            // 預設值
            selectListKind.First(x => x.Value == prod.fKID.ToString()).Selected = true;

            var vm = new v販售項目VM
            {
                fCID = prod.fCID,
                fPID = prod.fPID,
                fSID = prod.fSID,
                fKID = prod.fKID,
                f項目名稱 = prod.f項目名稱,
                f項目內容 = prod.f項目內容,
                f項目照片 = prod.f項目照片,
                f上架 = prod.f上架,
                f價格 = prod.f價格,

                style = selectListStyle,
                kind = selectListKind
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult productEdit(v販售項目VM vm)
        {
            // 後端模型驗證
            if (ModelState.IsValid)
            {
                var prod = db.t販售項目.FirstOrDefault(p => p.fPID == vm.fPID);

                if (vm.image != null)
                {
                    // 照片更新
                    var 新項目照片地址 = (new 共用方法()).照片更新(vm.image, Server.MapPath("~/"), CDictionary.照片存檔位置_項目, prod.f項目照片);
                    prod.f項目照片 = 新項目照片地址;
                }

                prod.fSID = vm.fSID;
                prod.fKID = vm.fKID;
                prod.f項目名稱 = vm.f項目名稱;
                prod.f項目內容 = vm.f項目內容;
                prod.f上架 = vm.f上架;
                prod.f價格 = vm.f價格;
                // 儲存DB
                db.SaveChanges();

                // 從販售項目選出私廚風格
                var 私廚風格 = (new Models.Prod.Method()).從販售項目選出私廚風格(vm.fCID);
                // 從販售項目選出私廚服務種類
                var 私廚服務種類 = (new Models.Prod.Method()).從販售項目選出私廚服務種類(vm.fCID);

                // 2.變更私廚風格
                // 3.變更私廚服務種類
                // 找到此私廚
                var chef = db.t私廚.FirstOrDefault(c => c.fCID == vm.fCID);
                chef.f風格 = 私廚風格;

WebApplication1/Views/Prod/calendar.cshtml
@model WebApplication1.ViewModels.Prod.v可預訂時間VM

@{
    ViewBag.Title = "設定可預訂時間";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


@section Breadcumb {
    @{Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="container contact-area section-padding-0-80">
    <div class="text-right mt-5"><a href="@Url.Action("center","Acc")" class="mr-5"><i class="fa fa-share" aria-hidden="true"></i> 返回會員中心</a></div>

    @using (Html.BeginForm("calendar", "Prod", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(vm => vm.fCID)

        <div id="calendar">
            <h4>2020年11月</h4>
            <a href="##" rel="external nofollow" class="a1">
                <i class="fa fa-chevron-left"
                   aria-hidden="true"></i>
            </a>
            <a href="##" rel="external nofollow" class="a2">
                <i class="fa fa-chevron-right"
                   aria-hidden="true"></i>
            </a>
            <ul class="week">
                <li>日</li>
                <li>一</li>
                <li>二</li>
                <li>三</li>
                <li>四</li>
                <li>五</li>
                <li>六</li>
            </ul>
            <ul class="dateList"></ul>
            <div><p class="text-center mt-4"><i class="fa fa-square-o" aria-hidden="true"></i> 不可預定　<i class="fa fa-square" style="color:#5ab496" aria-hidden="true"></i> 可預定　<i class="fa fa-square" style="color:#ffa943" aria-hidden="true"></i> 已被預定(不可修改)</p></div>
        </div>
        @* 取得新可預訂時間字串 ArrGetNewTime *@
        <input type="hidden" class="form-control" id="addtime" name="ArrGetNewTime" value="">
        @* 取得待刪除時間字串 ArrGetDeletedTime *@
        <input type="hidden" class="form-control" id="canceltime" name="ArrGetDeletedTime" value="">
        <div class="col-12 text-center">
            <button id="save" class="btn delicious-btn mt-30" type="submit">儲存</button>
        </div>

    }
</div>

@if (TempData[WebApplication1.Models.Common.CDictionary.TK_Msg_SaveCalendar] != null)
{
    <div id="savesuccess" class="popstyle" style="display: none;">
        <i class="fa fa-check successstatus"
           style="font-size: 28px;line-height: 60px;"></i>
        <h5><span class="successstatus">@TempData[WebApplication1.Models.Common.CDictionary.TK_Msg_SaveCalendar]</span></h5>
    </div>
}

@section scripts {
    <script>

        $(function () {
            var EnableStr = '@String.Join("|", Model.ArrEnable)';

            var disableStr = '@String.Join("|", Model.ArrUnable)';

            var available = EnableStr.split('|');
            //var available = ["2020-11-18-1", "2020-11-19-2", "2020-11-20-1", "2020-11-4-2", "2020-11-5-2", "2020-11-6-1"]; //資料庫給有空的時間
            var booked = disableStr.split('|');
            //var booked = ["2020-11-25-1", "2020-11-26-2", "2020-11-27-1"]; //資料庫給已被預訂的時間

            //必要的資料
            //今天的年 月 日 ；本月的總天數；本月第一天是周幾？？？
            var iNow = 0;

            function run(n) {

                var oDate = new Date(); //定義時間
                oDate.setMonth(oDate.getMonth() + n);//設定月份
                var year = oDate.getFullYear(); //年
                var month = oDate.getMonth(); //月
                var today = oDate.getDate(); //日

                //計算本月有多少天
                var allDay = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month];

                //判斷閏年
                if (month == 1) {
                    if (year % 4 == 0 && year % 100 != 0 || year % 400 == 0) {
                        allDay = 29;
                    }
                }

                //判斷本月第一天是星期幾
                oDate.setDate(1); //時間調整到本月第一天
                var week = oDate.getDay(); //讀取本月第一天是星期幾

                //console.log(week);
                $(".dateList").empty();//每次清空
                //插入空白

                for (var i = 0; i < week; i++) {
                    $(".dateList").append("<li></li>");
                }

                //日期插入到dateList
                for (var i = 1; i <= allDay; i++) {
                    $(".dateList").append(`
<li>
    <input type="button" value="${i}" class="nobuttonstyly"><br>
    <input type="button" value="午" class="nobuttonstyly period" id="${year}A${month + 1}A${i}-1">
    <input type="button" value="晚" class="nobuttonstyly period" id="${year}A${month + 1}A${i}-2">
</li>`)
                }

                for (let item of available) {
                    item = item.replaceAll('/', 'A');
                    $(`#${item}`).attr('class', 'period nobuttonstyly periodclicked');

                }
                for (let item of booked) {
                    item = item.replaceAll('/', 'A');
                    $(`#${item}`).attr('class', 'period nobuttonstyly booked');

                }

                var allinputvalue = "";
                var canceltime = "";
                $('.period').click(function () {
                    var inputvalue = this.id.replaceAll('A','/');

                    if ($(this).hasClass('periodclicked') && available.includes(inputvalue)) {
                        $(this).attr('class', 'period nobuttonstyly');
                        allinputvalue = allinputvalue.replace(`${inputvalue},`, "");
                        canceltime += inputvalue + ",";
                        $('#addtime').val(allinputvalue);
                        $('#canceltime').val(canceltime);
                    }
                    else if (!$(this).hasClass('periodclicked') && available.includes(inputvalue)) {
                        $(this).attr('class', 'period nobuttonstyly periodclicked');
                        canceltime = canceltime.replace(`${inputvalue},`, "");
                        $('#canceltime').val(canceltime);
                    }

                    else if ($(this).hasClass('periodclicked')) {
                        $(this).attr('class', 'period nobuttonstyly');
                        allinputvalue = allinputvalue.replace(`${inputvalue},`, "");
                        $('#addtime').val(allinputvalue);
                    }
                    else if ($(this).hasClass('booked')) {

                    }
                    else {
                        $(this).attr('class', 'period nobuttonstyly periodclicked');
                        allinputvalue += inputvalue + ",";
                        canceltime = canceltime.replace(`${inputvalue},`, "");
                        $('#canceltime').val(canceltime);
                        $('#addtime').val(allinputvalue);
                    }

                });

                //定義標題日期
                $("#calendar h4").text(year + "年" + (month + 1) + "月");
            };
            run(0);

            $(".a1").click(function () {
                iNow--;
                run(iNow);
            });

            $(".a2").click(function () {
                iNow++;
                run(iNow);
            })


        });
        @* 成功訊息 非同步 modal (有空做) *@

        @*$('#save').click(function () {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("calendar", "Prod")',
                data: {
                    fCID : $('#fCID').val(),
                    ArrGetNewTime: $('#addtime').val(),
                    ArrGetDeletedTime: $('#canceltime').val()
                },
                dataType: 'json',
                    success: function (data, status, xhr) {
                        $("#savesuccess").show().delay(1000).hide(300);
                    },
                    error: function (xhr, textstatus, data) {
                        alert(data);
                    }
                })

        })*@

        @if (TempData[WebApplication1.Models.Common.CDictionary.TK_Msg_SaveCalendar] != null)
        {
            @:$("#savesuccess").show().delay(1000).hide(300);
        }

    </script>
}

WebApplication1/Views/Prod/dishCreate.cshtml
@model WebApplication1.ViewModels.Prod.v菜品VM
@{
    ViewBag.Title = "新增 - " + Model.項目名稱 + " - 菜色";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

@using (Html.BeginForm(
    "dishCreate",
    "Prod",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(vm => vm.fPID)
    @Html.HiddenFor(vm => vm.fVID)
    <!-- ##### memberinfo Start ##### -->
    <div class="contact-area section-padding-0-80">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="contact-form-area">
                        <form action="#" method="post" enctype="multipart/form-data">
                            <div class="row">
                               
                                <div class="picbg mt-5 mb-2">
                                    <img id="foodimg" class="img-style"
                                         src="@Model.f菜品照片"  onerror="this.src='https://icon-library.com/images/no-image-icon/no-image-icon-5.jpg'" style="margin-bottom: 0px">
                                    <label class="btn delicious-btn nobord" for="file" style="width:300px;">上傳圖片</label>
                                    <input class="hide" id="file" type="file" style="display:none" name="image" multiple accept="image/gif, image/png, image/jpg, image/jpeg" />
                                </div>

                                <div class="col-12 " style="margin-top:400px;"></div><!--先留著 不然圖片會跑掉-->

                                <div class="col-12 mt-5">
                                    @Html.EditorFor(model => model.f菜品名稱, new { htmlAttributes = new { @class = "form-control", @placeholder = "菜色名稱" } })
                                    @Html.ValidationMessageFor(model => model.f菜品名稱, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-12 mt-2">
                                    @*<textarea name="productinfo" class="form-control" id="chef-summary" cols="30"
                                        rows="10" placeholder="詳細菜色內容" required></textarea>*@
                                    @Html.TextAreaFor(model => model.f菜品簡介, new { @class = "form-control", @placeholder = "詳細菜色內容", @id = "chef-summary", @cols = 30, @rows = 10 })
                                    @Html.ValidationMessageFor(model => model.f菜品簡介, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-12 mt-2">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-12 text-center">
                                    <button class="btn delicious-btn mt-30" type="submit" value="Create">儲存</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!-- ##### memberinfo End ##### -->


@section scripts {
    <script>
        $("#file").change(function () {
            readURL(this);
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#foodimg").attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}