WebApplication1/Controllers/FontendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    
    public class FontendController : Controller
    {
        // GET: Fontend

        // 登入
        public ActionResult login()
        {
            return View();
        }

        #region 會員中心{ [註冊 註冊成功] [編輯基本資料 編輯私廚簡介] [會員中心(一般) 會員中心(私廚)] [我的最愛] }

        // 註冊
        public ActionResult register()
        {
            return View();
        }

        // 註冊成功
        public ActionResult registersuccess()
        {
            return View();
        }

        // 編輯基本資料
        public ActionResult memberinfo()
        {
            return View();
        }

        // 編輯私廚簡介
        public ActionResult chefedit()
        {
            return View();
        }

        // 會員中心(私廚)
        public ActionResult chefcenter()
        {
            return View();
        }

        // 會員中心(一般)
        public ActionResult membercenter()
        {
            return View();
        }

        // 我的最愛
        public ActionResult favorite()
        {
            return View();
        }

        #endregion

        #region 交易紀錄{ [儲值點數 儲值成功] [交易紀錄] [私廚資訊] [客戶資訊] [填寫評價] [品項訂購]}

        // 儲值點數
        public ActionResult buypoint() // OK 需測試
        {
            return View();
        }

        // 儲值成功
        public ActionResult buypointsuccess() // OK 需測試
        {
            return View();
        }

        // 品項訂購
        public ActionResult salesitem()
        {
            return View();
        }

        // 交易紀錄
        public ActionResult transaction() // OK 需測試
        {
            return View();
        }

        // 私廚資訊
        public ActionResult chefinfo() // OK 需測試
        {
            return View();
        }

        // 客戶資訊
        public ActionResult clientinfo() // OK 需測試
        {
            return View();
        }

        // 填寫評價
        public ActionResult evaluate() // OK 需測試
        {
            return View();
        }

        #endregion

        #region 私廚{ [私廚販售項目清單] [新增販售項目] [新增菜色] [設定可預訂時間] }

        // 私廚販售項目清單
        public ActionResult salesitemlist()
        {
            return View();
        }

        // 新增販售項目
        public ActionResult productinfo()
        {
            return View();
        }

        // 新增 - 販售項目 - 菜色
        public ActionResult dishesinfo()
        {
            return View();
        }

        // 設定可預訂時間
        public ActionResult calendar()
        {
            return View();
        }

        #endregion

        // 首頁 
        public ActionResult index()
        {
            return View();
        }

        // 搜尋結果 
        public ActionResult searchlist()
        {
            return View();
        }




    }
}

WebApplication1/Views/Fontend/buypointsuccess.cshtml
@{
    ViewBag.Title = "儲值成功";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <span>將於<span id="seconds"></span>秒後為您跳轉至交易紀錄頁面。</span><br><br>
                <span>
                    或者自行點擊<a href="@Url.Action("buypoint", "Fontend")" class="single-contact-information">
                        <h6>交易紀錄</h6><!--交易紀錄好要改連結-->
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script>
        {
            let t = 6;
            function reciprocal() {
                t -= 1;
                document.getElementById('seconds').innerHTML = t;
                if (t == 0) {
                    location.href = "@Url.Action("buypoint", "Fontend")"; //之後交易紀錄好要改連結
                }
                // 不能在 IIFE 裡,會找不到 func
                setTimeout("reciprocal()", 1000);
            }
            window.onload = reciprocal;
        }
    </script>
}

WebApplication1/Views/Fontend/calendar.cshtml
@{
    ViewBag.Title = "設定可預訂時間";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="container contact-area section-padding-0-80">
    <form action="#" method="post">
        <div id="calendar">
            <h4>2020年11月</h4>
            <a href="##" rel="external nofollow" class="a1">
                <i class="fa fa-chevron-left"
                   aria-hidden="true"></i>
            </a>
            <a href="##" rel="external nofollow" class="a2">
                <i class="fa fa-chevron-right"
                   aria-hidden="true"></i>
            </a>
            <ul class="week">
                <li>日</li>
                <li>一</li>
                <li>二</li>
                <li>三</li>
                <li>四</li>
                <li>五</li>
                <li>六</li>
            </ul>
            <ul class="dateList"></ul>
            <div><p class="text-center mt-4"><i class="fa fa-square-o" aria-hidden="true"></i> 不可預定　<i class="fa fa-square" style="color:#ffa943" aria-hidden="true"></i> 可預定　<i class="fa fa-square" style="color:#c16315" aria-hidden="true"></i> 已被預定(不可修改)</p></div>
        </div>


        <input type="text" class="form-control" id="addtime" name="ArrGetNewTime" value="" style="display: none;">
        <input type="text" class="form-control" id="canceltime" name="ArrGetDeletedTime" value="" style="display: none;">
        <div class="col-12 text-center">
            <button class="btn delicious-btn mt-30" type="submit">儲存</button>
        </div>
    </form>
</div>

@section scripts {
    <script>
        $(function () {

            var available = ["2020-11-18-1", "2020-11-19-2", "2020-11-20-1", "2020-11-4-2", "2020-11-5-2", "2020-11-6-1"]; //資料庫給有空的時間
            var booked = ["2020-11-25-1", "2020-11-26-2", "2020-11-27-1"]; //資料庫給已被預訂的時間

            //必要的資料
            //今天的年 月 日 ；本月的總天數；本月第一天是周幾？？？
            var iNow = 0;

            function run(n) {

                var oDate = new Date(); //定義時間
                oDate.setMonth(oDate.getMonth() + n);//設定月份
                var year = oDate.getFullYear(); //年
                var month = oDate.getMonth(); //月
                var today = oDate.getDate(); //日

                //計算本月有多少天
                var allDay = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month];

                //判斷閏年
                if (month == 1) {
                    if (year % 4 == 0 && year % 100 != 0 || year % 400 == 0) {
                        allDay = 29;
                    }
                }

                //判斷本月第一天是星期幾
                oDate.setDate(1); //時間調整到本月第一天
                var week = oDate.getDay(); //讀取本月第一天是星期幾

                //console.log(week);
                $(".dateList").empty();//每次清空
                //插入空白

                for (var i = 0; i < week; i++) {
                    $(".dateList").append("<li></li>");
                }

                //日期插入到dateList
                for (var i = 1; i <= allDay; i++) {
                    $(".dateList").append(`
                            <li>
                                <input type="button" value="${i}" class="nobuttonstyly"><br>
                                <input type="button" value="午" class="nobuttonstyly period" id="${year}-${month + 1}-${i}-1">
                                <input type="button" value="晚" class="nobuttonstyly period" id="${year}-${month + 1}-${i}-2">
                            </li>`)
                }

                for (const item of available) {
                    $(`#${item}`).attr('class', 'period nobuttonstyly periodclicked');

                }
                for (const item of booked) {
                    $(`#${item}`).attr('class', 'period nobuttonstyly booked');

                }

                var allinputvalue = "";
                var canceltime = "";
                $('.period').click(function () {
                    var inputvalue = this.id;

                    if ($(this).hasClass('periodclicked') && available.includes(inputvalue)) {
                        $(this).attr('class', 'period nobuttonstyly');
                        allinputvalue = allinputvalue.replace(`${inputvalue},`, "");
                        canceltime += inputvalue + ",";
                        $('#addtime').val(allinputvalue);
                        $('#canceltime').val(canceltime);
                    }
                    else if (!$(this).hasClass('periodclicked') && available.includes(inputvalue)) {
                        $(this).attr('class', 'period nobuttonstyly periodclicked');
                        canceltime = canceltime.replace(`${inputvalue},`, "");
                        $('#canceltime').val(canceltime);
                    }

                    else if ($(this).hasClass('periodclicked')) {
                        $(this).attr('class', 'period nobuttonstyly');
                        allinputvalue = allinputvalue.replace(`${inputvalue},`, "");
                        $('#addtime').val(allinputvalue);
                    }
                    else if ($(this).hasClass('booked')) {

                    }
                    else {
                        $(this).attr('class', 'period nobuttonstyly periodclicked');
                        allinputvalue += inputvalue + ",";
                        canceltime = canceltime.replace(`${inputvalue},`, "");
                        $('#canceltime').val(canceltime);
                        $('#addtime').val(allinputvalue);
                    }

                });

                //定義標題日期
                $("#calendar h4").text(year + "年" + (month + 1) + "月");
            };
            run(0);

            $(".a1").click(function () {
                iNow--;
                run(iNow);
            });

            $(".a2").click(function () {
                iNow++;
                run(iNow);
            })
        });

    </script>
}

WebApplication1/Views/Fontend/chefedit.cshtml
@{
    ViewBag.Title = "編輯私廚簡介";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="#" method="post">
                        <div class="row">
                            <div class="col-12 mt-5">
                                <select name="service-area" id="service-area" class="form-control-option" required>
                                    <option disabled selected>服務地區</option>
                                    <option value="1">台北市</option>
                                    <option value="2">新北市</option>
                                    <option value="3">基隆市</option>
                                    <option value="4">桃園市</option>
                                    <option value="5">新竹市</option>
                                    <option value="6">新竹縣</option>
                                    <option value="7">苗栗縣</option>
                                    <option value="8">台中市</option>
                                    <option value="9">彰化縣</option>
                                    <option value="10">南投縣</option>
                                    <option value="11">雲林縣</option>
                                    <option value="12">嘉義市</option>
                                    <option value="13">嘉義縣</option>
                                    <option value="14">台南市</option>
                                    <option value="15">高雄市</option>
                                    <option value="16">屏東縣</option>
                                    <option value="17">宜蘭縣</option>
                                    <option value="18">花蓮縣</option>
                                    <option value="19">台東縣</option>
                                    <option value="20">澎湖縣</option>
                                    <option value="21">金門縣</option>
                                    <option value="22">連江縣</option>
                                </select>
                            </div>
                            <div class="col-12 mt-4">
                                <textarea name="message" class="form-control" id="chef-summary" cols="30" rows="10"
                                          placeholder="私廚簡介" required></textarea>
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn delicious-btn mt-30" type="submit">儲存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Fontend/register.cshtml
@{
    ViewBag.Title = "註冊";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### Register Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-area">
                    <form action="@Url.Action("registersuccess", "Fontend")" method="post">
                        <div class="row">
                            <div class="col-12 mt-5">
                                <input type="text" class="form-control" id="account" placeholder="帳號" required>
                            </div>
                            <div class="col-12 mt-2">
                                <input type="password" class="form-control" id="password1" placeholder="密碼"
                                       required>
                            </div>
                            <div class="col-12 mt-2">
                                <input type="password" class="form-control" id="password2" placeholder="確認密碼"
                                       onchange="checkpw()" required>
                            </div>
                            <div id="msg" class="msg-style2"></div>
                            <div class="col-12 mt-2">
                                <input type="email" class="form-control" id="email" placeholder="電子郵件" required>
                            </div>

                            <div class="col-12 text-center">
                                <button class="btn delicious-btn mt-30" type="submit" id="btn">註冊</button>
                            </div>
                            <div class="col-12 text-right mt-4">
                                <span>
                                    已經有帳號了？點擊 <a href="@Url.Action("registersuccess", "Fontend")" class="single-contact-information">
                                        <h6>登入</h6>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Register End ##### -->

@section scripts {
    <script>
        function checkpw() {
            var pw1 = $('input[id=password1]').val();
            var pw2 = $('input[id=password2]').val();
            if (pw1 != pw2) {
                $('#msg').html('密碼與確認密碼不一致。');
                $("#btn").attr("disabled", true);
            }
            else {
                $('#msg').html('');
                $("#btn").attr("disabled", false);
            }

        }
    </script>
}

WebApplication1/Views/Fontend/registersuccess.cshtml
@{
    ViewBag.Title = "註冊成功";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<!-- ##### Register Start ##### -->
<div class="contact-area section-padding-0-80">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mt-5">
                <span>將於<span id="seconds"></span>秒後為您跳轉至登入頁面。</span><br><br>
                <span>
                    或者自行點擊<a href="@Url.Action("register", "Fontend")" class="single-contact-information">
                        <h6>登入</h6>
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>
<!-- ##### Register End ##### -->

@section scripts {

    <script>
        {
            let t = 6;
            function reciprocal() {
                t -= 1;
                document.getElementById('seconds').innerHTML = t;
                if (t == 0) {
                    location.href = "@Url.Action("register", "Fontend")"; //之後交易紀錄好要改連結
                }
                setTimeout("reciprocal()", 1000);
            }
            window.onload = reciprocal;
        }
    </script>
}

WebApplication1/Views/Fontend/salesitemlist.cshtml
@{
    ViewBag.Title = "販售項目";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

@section Breadcumb {
    @{ Html.RenderPartial("~/Views/Shared/_Breadcumb一般.cshtml"); }
}

<div class="container mt-5 mb-5">

    <a href="productinfo.html">
        <span class="newitem">
            <i class="fa fa-plus" aria-hidden="true"></i>
            新增販售項目
        </span>
    </a>
</div>
<div class="container">

    <div class="accordions mb-80" id="accordion" role="tablist" aria-multiselectable="true">

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" class="" aria-expanded="true" aria-controls="collapseOne" data-toggle="collapse"
                   data-parent="#accordion" href="#collapseOne">
                    1.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseOne" class="accordion-content collapse ">
                <table>
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/bg-img/insta1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="custom-control custom-checkbox ">
                                <input type="checkbox" class="custom-control-input" id="customCheck1">
                                <label class="custom-control-label" for="customCheck1"><a>上架</a></label>
                            </div>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta2.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta3.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("dishesinfo","Fontend")"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" class="collapsed" aria-expanded="true" aria-controls="collapseTwo"
                   data-parent="#accordion" data-toggle="collapse" href="#collapseTwo">
                    2.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseTwo" class="accordion-content collapse">
                <table class="product_detail ">
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/bg-img/insta4.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="ingredients">
                                <div class="custom-control custom-checkbox ">
                                    <input type="checkbox" class="custom-control-input" id="customCheck2">
                                    <label class="custom-control-label" for="customCheck2"><a>上架</a></label>
                                </div>
                            </div>
                            <a href="#" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="@Url.Action("productinfo","Fontend")" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta5.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="@Url.Action("productinfo","Fontend")"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/bg-img/insta6.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>

        <!-- Single Accordian Area -->
        <div class="panel single-accordion">
            <h6>
                <a role="button" aria-expanded="true" aria-controls="collapseThree" class="collapsed"
                   data-parent="#accordion" data-toggle="collapse" href="#collapseThree">
                    3.套餐/課程名稱-風格-服務項目
                    <span class="accor-open"><i class="fa fa-plus" aria-hidden="true"></i></span>
                    <span class="accor-close"><i class="fa fa-minus" aria-hidden="true"></i></span>
                </a>
            </h6>
            <div id="collapseThree" class="accordion-content collapse">
                <table class="product_detail ">
                    <tr>
                        <td rowspan="3" style="width:20%; padding: 0; min-width: 200px;" class="img-style5"
                            background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>主要內容</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border" style="width: 10%;">
                            <div class="custom-control custom-checkbox ">
                                <input type="checkbox" class="custom-control-input" id="customCheck3">
                                <label class="custom-control-label" for="customCheck3"><a>上架</a></label>
                            </div>
                            <a href="#" class="pd1px"><i class="fa fa-plus"></i><span class="pl-2"> 菜色</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#" class="pd1px"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td" style="width: 100px;min-width: 100px;"><b>價格:</b></td>
                    <td class="product_td">NT$500/人</td>
                    <tr>
                        <td class="product_td table-bottom" style="width:10%;"><b>詳細內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色1</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容:</b></td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>

                    <tr>
                        <td rowspan="3" style="padding: 0;" class="img-style5" background="/Content/img/james-img/1.jpg"></td>
                        <td colspan="2" class="product_td">
                            <h6>菜色2</h6>
                        </td>
                        <td rowspan="3" class="text-left pl-4 table-border">

                            <a href="#"><i class="fa fa-edit"></i><span class="pl-2">編輯</span></a><br>
                            <a href="#"><i class="fa fa-trash"></i><span class="pl-2"> 刪除</span></a>
                        </td>
                    </tr>
                    <td class="product_td"><b>菜名:</b></td>
                    <td class="product_td">宮保雞丁</td>
                    <tr>
                        <td class="product_td table-bottom"><b>菜色內容</b>:</td>
                        <td class="product_td table-bottom">詳細內容詳細內容詳細內容詳細內詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容詳細內容容詳細內容詳細內容</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>